export const ENABLE_WEEKEND_PLANNER_DIRECT_ENTRY =
  process.env.NEXT_PUBLIC_ENABLE_WEEKEND_PLANNER_DIRECT_ENTRY === "true";

export const ENABLE_ANONYMOUS_PLANNER_ACTIVATION_V1 =
  process.env.NEXT_PUBLIC_ANONYMOUS_PLANNER_ACTIVATION_V1_ENABLED === "true";
